name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # 新增：关键验证步骤——打印CI环境的文件列表和路径，排查文件是否存在
      - name: Verify CI env & file structure
        run: |
          ls -la  # 列出根目录所有文件，确认deepseek_client.py是否存在
          pwd     # 打印当前工作目录，确认路径是否正确
          echo "初始PYTHONPATH: $PYTHONPATH"  # 打印初始环境变量

      - name: Lint (flake8)
        run: |
          flake8 --max-line-length=100 || true

      - name: Run tests
        run: |
          pip install pytest
          # 更强制的写法：内联设置PYTHONPATH，直接跟在pytest前，100%生效
          PYTHONPATH=$(pwd) pytest -q
