name: CI

on:
  push:
    branches: [ main, feat/deploy-ci ]  # 加feat/deploy-ci，推这个分支也触发CI
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
          # 新增兜底：把项目根写入Python官方pth文件，永久加入模块路径
          echo $(pwd) > $(python -c "import site; print(site.getsitepackages()[0])")/ai-project.pth

      # 新增：验证CI环境的文件结构
      - name: Verify CI environment
        run: |
          ls -la
          echo "Current directory: $(pwd)"

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test with pytest
        run: |
          # 核心修复：改用python -m pytest，严格继承PYTHONPATH
          PYTHONPATH=$(pwd) python -m pytest -v --tb=short
